defaultBaseImage: gcr.io/distroless/static:nonroot
builds:
  - id: controller
    main: ./cmd/controller
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
