apiVersion: v2
name: karpenter
description: Karpenter node autoscaling for UpCloud cloud servers.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - karpenter
  - autoscaling
  - upcloud
home: https://github.com/kubekanvas/karpenter-provider-upcloud
sources:
  - https://github.com/kubekanvas/karpenter-provider-upcloud
